// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmlwgM5vi6gEgIvRWfd5gTZ5sqK9OsS4',
    appId: '1:973267061723:web:ce9bfaf846c66d08bcb5fe',
    messagingSenderId: '973267061723',
    projectId: 'chatbot-73dcd',
    authDomain: 'chatbot-73dcd.firebaseapp.com',
    storageBucket: 'chatbot-73dcd.appspot.com',
    measurementId: 'G-8S96QN1RRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75_JFv-vtkroFwb3knecfZWUGgGdfQCY',
    appId: '1:973267061723:android:2de2c34fe3d79552bcb5fe',
    messagingSenderId: '973267061723',
    projectId: 'chatbot-73dcd',
    storageBucket: 'chatbot-73dcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-g1Tzks2UUcWunYTO3Do6FI0GeH3ueA',
    appId: '1:973267061723:ios:3655b30e9f6b3a22bcb5fe',
    messagingSenderId: '973267061723',
    projectId: 'chatbot-73dcd',
    storageBucket: 'chatbot-73dcd.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );
}
